= Docker-Compose AI
:toc:
:sectnums:

== Setup

This setup describes the steps required for runnning a local AI with WSL and docker-compose, using a NVIDIA GPU for acceleration.

NOTE: Make sure that the NVIDIA drivers are installed properly (https://www.nvidia.com/en-us/drivers/).

=== Setting up WSL

Setting up WSL is recommended, running the AI on a Windows installation.

Required _Windows Features_:

* Virtual Machine Platform
* Windows Subsystem for Linux

Proceed with the WSL OS installation by executing the following commands in a terminal:

.PowerShell command for installing WSL using the default OS (Ubuntu)
[source, powershell]
-----
wsl --install
-----

=== Setting up NVIDIA graphics drivers

The following steps are required to use the NVIDIA GPU inside a docker container.


.Adding the gpg key for the nvidia container toolkit repository
[source, shell]
-----
curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
-----

.Adding the nvidia container toolkit repository
[source, shell]
-----
curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
-----

.Installation of the nvidia container toolkit
[source, shell]
-----
sudo apt-get update && sudo apt-get install -y nvidia-container-toolkit
-----

=== Setting up docker-compose

The current setup uses docker-compose to work. Please install docker compose, using the following commands:

.Docker and docker-compose installation for Ubuntu 
[code, shell]
-----
sudo apt install docker.io docker-compose-v2
-----

== Starting the AI

WARNING: Before starting docker-compose run the `init.sh` file in order to create a random password, used to secure the services.

Starting the AI is done by calling:

.Starting the docker-compose.yml in detached mode (-d)
[source, shell]
-----
docker compose up -d
-----

NOTE: You may have to restart docker by executing _sudo systemctl restart docker_ if the GPU is not found.

The Open-WebUI should be accessible through http://127.0.0.1:8080/ after a short while. A wizard for creating an initial admin account will start during the first login.

The Ollama is accessible through http://127.0.0.1:11434/ for hooking up your IDE, if needed.

=== How to proceed

* Create an account in http://127.0.0.1:8080/[Open-WebUI] using
* Pull the images `bge-m3:latest` and `mistral-nemo:latest`, required for the LightRAG Knowledge Graph generation

== Monitoring

.Docker monitoring command
[source, shell]
-----
docker stats
-----

.GPU monitoring command
[source, shell]
-----
nvidia-smi
-----

NOTE: You may use _watch_ plus the command to automatically refresh the output.
