= Docker-Compose AI
:toc:
:sectnums:

== Setup

This setup describes the steps required for runnning a local AI with WSL and docker-compose, using a NVIDIA GPU for acceleration.

NOTE: Make sure that the NVIDIA drivers are installed properly (https://www.nvidia.com/en-us/drivers/).

=== Setting up WSL

Setting up WSL is recommended, running the AI on a Windows installation.

Required _Windows Features_:

* Virtual Machine Platform
* Windows Subsystem for Linux

Procceed with the WSL OS installation by execting following commands in a terminal, after enabling the required _Windows Features_:

.Powershell command for installing WSL using the default OS (Ubuntu)
[code, powershell]
-----
wsl --install
-----

=== Setting up NVIDIA graphics drivers

The following steps are required in order to use the NVIDIA GPU inside a docker container.


.Adding the gpg key for the nvidia container toolkit repository
[source, sh]
-----
curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
-----

.Adding the nvidia container toolkit repository
[source, sh]
-----
curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
-----

.Installation of the nvidia container toolkit
[source, sh]
-----
sudo apt-get update && sudo apt-get install -y nvidia-container-toolkit
-----

=== Setting up docker-compose

The current setup uses docker-compose in order to work. Please install docker compose, using the following commands:

.Docker and docker-compose installation for Ubuntu 
[code, shell]
-----
sudo apt install docker.io docker-compose-v2
-----

== Starting the AI

Starting the AI is done by calling:

.Starting the docker-compose.yml in detached mode (-d)
[source, sh]
-----
docker compose up -d
-----

NOTE: You may have to restart docker by executing _sudo systemctl restart docker_ if the GPU is not found.

The Open-WebUI should be accessible through http://127.0.0.1:8080/ after a short while. A wizard for creating an initial admin account will start during the first login.

The Ollama is accessible through http://127.0.0.1:11434/ for hooking up your IDE, if needed.

